### ISSUE TITLE
请问电脑端与手机端传递的时间差是多少？

### ISSUE THREAD

**Issue by iKineticate** [doraemonkeys/WindSend#12]
问题现象：电脑与手机相差10秒后，手机则显示"没有找到可用的服务器"

是否打算提供解决办法：电脑端CMD刷新时间，不同手机系统刷新时间的办法😂（感觉有点困难）
是否打算添加提醒：手机端显示语句"没有找到可用的服务器"的下一行添加"注意：电脑端与手机端时间需同步且时间差不超过?秒"等之类的提示或帮助？👍

感谢老哥的软件！😘

**Comment by doraemonkeys** [comment]
现在10秒太严格了，以后会调整到10分钟。目前正在重构界面和加一些新功能，后面调整完毕会一起发一个新版本
![Screenshot_2023-12-15-22-46-42-078_com.example.wind_send.jpg](https://github.com/doraemonkeys/WindSend/assets/87186997/5ecbcbc9-733c-4e59-8a9b-22987a80f5a6)

**Comment by iKineticate** [comment]
> 现在10秒太严格了，以后会调整到10分钟。目前正在重构界面和加一些新功能，后面调整完毕会一起发一个新版本 ![Screenshot_2023-12-15-22-46-42-078_com.example.wind_send.jpg](https://private-user-images.githubusercontent.com/87186997/290854838-5ecbcbc9-733c-4e59-8a9b-22987a80f5a6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTIwOTMsIm5iZiI6MTcwMjY1MTc5MywicGF0aCI6Ii84NzE4Njk5Ny8yOTA4NTQ4MzgtNWVjYmNiYzktNzMzYy00ZTU5LThhOWItMjI5ODdhODBmNWE2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE0NDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MTdlMDUxMDc5ZTVhYjk2MzU0MjFlMjgzZGVhNDgwMTFiN2JiNWNkN2ZmY2M2OTkxMDI2MjAwOTI0YjQzNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4YB2qLRxKxmcArUPnZoXgmCudog_9tn6lZOTgin8OYI)

10分钟会不会太长了？（受虐滑稽），要不折中一下2~5分钟？（或者允许用户高级自定义时间差？）（受虐滑稽）

新的APP界面太好看了吧！还有深浅色适配、自选颜色主题！！！😍

请问"设备1"、"设备2"、"设备3"等是默认名称还是默认填写电脑设备的名称？

辛苦老哥了！👍👍

**Comment by doraemonkeys** [comment]
> > 现在10秒太严格了，以后会调整到10分钟。目前正在重构界面和加一些新功能，后面调整完毕会一起发一个新版本 ![Screenshot_2023-12-15-22-46-42-078_com.example.wind_send.jpg](https://private-user-images.githubusercontent.com/87186997/290854838-5ecbcbc9-733c-4e59-8a9b-22987a80f5a6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTIwOTMsIm5iZiI6MTcwMjY1MTc5MywicGF0aCI6Ii84NzE4Njk5Ny8yOTA4NTQ4MzgtNWVjYmNiYzktNzMzYy00ZTU5LThhOWItMjI5ODdhODBmNWE2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE0NDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MTdlMDUxMDc5ZTVhYjk2MzU0MjFlMjgzZGVhNDgwMTFiN2JiNWNkN2ZmY2M2OTkxMDI2MjAwOTI0YjQzNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4YB2qLRxKxmcArUPnZoXgmCudog_9tn6lZOTgin8OYI)
> 
> 10分钟会不会太长了？（受虐滑稽），要不折中一下2~5分钟？（或者允许用户高级自定义时间差？）（受虐滑稽）
> 
> 新的APP界面太好看了吧！还有深浅色适配、自选颜色主题！！！😍
> 
> 请问"设备1"、"设备2"、"设备3"等是默认名称还是默认填写电脑设备的名称？
> 
> 辛苦老哥了！👍👍

我在Release里面发布了一个arm64的临时版本(时间差10分钟)，新版本可能需要等一段时间了，最近破事太多（受虐滑稽）

**Comment by iKineticate** [comment]
> > > 现在10秒太严格了，以后会调整到10分钟。目前正在重构界面和加一些新功能，后面调整完毕会一起发一个新版本 ![Screenshot_2023-12-15-22-46-42-078_com.example.wind_send.jpg](https://private-user-images.githubusercontent.com/87186997/290854838-5ecbcbc9-733c-4e59-8a9b-22987a80f5a6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTIwOTMsIm5iZiI6MTcwMjY1MTc5MywicGF0aCI6Ii84NzE4Njk5Ny8yOTA4NTQ4MzgtNWVjYmNiYzktNzMzYy00ZTU5LThhOWItMjI5ODdhODBmNWE2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE0NDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MTdlMDUxMDc5ZTVhYjk2MzU0MjFlMjgzZGVhNDgwMTFiN2JiNWNkN2ZmY2M2OTkxMDI2MjAwOTI0YjQzNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4YB2qLRxKxmcArUPnZoXgmCudog_9tn6lZOTgin8OYI)
> > 
> > 
> > 10分钟会不会太长了？（受虐滑稽），要不折中一下2~5分钟？（或者允许用户高级自定义时间差？）（受虐滑稽）
> > 新的APP界面太好看了吧！还有深浅色适配、自选颜色主题！！！😍
> > 请问"设备1"、"设备2"、"设备3"等是默认名称还是默认填写电脑设备的名称？
> > 辛苦老哥了！👍👍
> 
> 我在Release里面发布了一个arm64的临时版本(时间差10分钟)，新版本可能需要等一段时间了，最近破事太多（受虐滑稽）

嗯嗯，完全不急，现版本的功能也够用💪，感谢老哥💕💕
