### ISSUE TITLE
macOS run init_global_config error: 不支持的操作系统

### ISSUE THREAD

**Issue by xgdgsc** [doraemonkeys/WindSend#18]
```
(base) ➜  release git:(main) RUST_BACKTRACE=1 ./wind_send
thread '<unnamed>' panicked at src/config.rs:122:13:
init_global_config error: 不支持的操作系统
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: std::sync::once::Once::call_once::{{closure}}
   3: std::sys_common::once::queue::Once::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/once/queue.rs:183:21
   4: wind_send::async_main::{{closure}}
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::context::runtime::enter_runtime
   7: tokio::runtime::runtime::Runtime::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at /Users/USERNAME/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/inline_lazy.rs:30:16:
Once instance has previously been poisoned
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: std::sys_common::once::queue::Once::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/once/queue.rs:155:21
   3: wind_send::systray::loop_systray
   4: wind_send::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by xgdgsc** [comment]
Go编译报
```
package github.com/doraemonkeys/WindSend
        imports github.com/lxn/win: build constraints exclude all Go files in /Users/USERNAME/go/pkg/mod/github.com/lxn/win@v0.0.0-20210218163916-a377121e959e
package github.com/doraemonkeys/WindSend
        imports golang.org/x/sys/windows: build constraints exclude all Go files in /Users/USERNAME/go/pkg/mod/golang.org/x/sys@v0.17.0/windows
```
应该目前还是只支持windows

**Comment by doraemonkeys** [comment]
> ```
> (base) ➜  release git:(main) RUST_BACKTRACE=1 ./wind_send
> thread '<unnamed>' panicked at src/config.rs:122:13:
> init_global_config error: 不支持的操作系统
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
>    1: core::panicking::panic_fmt
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
>    2: std::sync::once::Once::call_once::{{closure}}
>    3: std::sys_common::once::queue::Once::call
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/once/queue.rs:183:21
>    4: wind_send::async_main::{{closure}}
>    5: tokio::runtime::park::CachedParkThread::block_on
>    6: tokio::runtime::context::runtime::enter_runtime
>    7: tokio::runtime::runtime::Runtime::block_on
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> thread 'main' panicked at /Users/USERNAME/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0/src/inline_lazy.rs:30:16:
> Once instance has previously been poisoned
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
>    1: core::panicking::panic_fmt
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
>    2: std::sys_common::once::queue::Once::call
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/once/queue.rs:155:21
>    3: wind_send::systray::loop_systray
>    4: wind_send::main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```

rust版本的是编译成功了运行时报错吗？试试这个分支[18-macos-run-init_global_config-error](https://github.com/doraemonkeys/WindSend/tree/18-macos-run-init_global_config-error)能编译吗

**Comment by xgdgsc** [comment]
这个分支可以，正常编译运行 
[wind_send.zip](https://github.com/doraemonkeys/WindSend/files/14392605/wind_send.zip)
