### ISSUE TITLE
device_info_plus: ^10.0.0

### ISSUE THREAD

**Issue by xgdgsc** [doraemonkeys/WindSend#20]
flutter编译的时候说没有10的版本，改成 device_info_plus: ^9.0.0 可以编译运行mac和ios版，就是报错不清楚是因为模拟器网络的原因还是其他原因，我也没有ios设备。理论上mac版是能用的吗?不太懂flutter.
<img width="782" alt="截屏2024-02-25 08 57 40" src="https://github.com/doraemonkeys/WindSend/assets/1189869/e82076c7-32d8-4dff-a985-8fda3eae909c">
点复制：
<img width="781" alt="截屏2024-02-25 08 57 53" src="https://github.com/doraemonkeys/WindSend/assets/1189869/9228aad2-30b5-48e1-9955-6d6a50f50a3a">

**Comment by doraemonkeys** [comment]
@xgdgsc 上面的问题我已经在最新的commit尝试修复了。理论上是支持mac的，但是我这边没有相关的设备来测试，只能靠感觉🤣。

**Comment by xgdgsc** [comment]
mac第一个报错没了，第二个还是一样，ios点复制会崩溃:

```
A Dart VM Service on iPhone 15 Pro Max is available at:
http://127.0.0.1:57960/G6cC1jjW0ac=/
The Flutter DevTools debugger and profiler on iPhone 15 Pro Max is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:57960/G6cC1jjW0ac=/
flutter: \^[[38;5;196m┌─────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ SocketException: Failed host lookup: 'Unknown' (OS Error: nodename nor servname provided, or not known, errno = 8)<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ #0   _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)<…>
flutter: \^[[38;5;196m│ #1   _NativeSocket.connect (dart:io-patch/socket_patch.dart:984:12)<…>
flutter: \^[[38;5;196m│ #2   _RawSocket.connect (dart:io-patch/socket_patch.dart:1902:26)<…>
flutter: \^[[38;5;196m│ #3   RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)<…>
flutter: \^[[38;5;196m│ #4   RawSecureSocket.connect (dart:io/secure_socket.dart:282:22)<…>
flutter: \^[[38;5;196m│ #5   SecureSocket.connect (dart:io/secure_socket.dart:60:28)<…>
flutter: \^[[38;5;196m│ #6   Device.doCopyAction (package:wind_send/device.dart:401:35)<…>
flutter: \^[[38;5;196m│ #7   deviceItemChilden.<anonymous closure>.<anonymous closure> (package:wind_send/main.dart:770:45)<…>
flutter: \^[[38;5;196m│ #8   DeviceItem.commonActionFunc (package:wind_send/main.dart:581:25)<…>
flutter: \^[[38;5;196m│ #9   deviceItemChilden.<anonymous closure> (package:wind_send/main.dart:768:30)<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ 15:25:32.885 (+0:00:02.676064)<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ ⛔ commonActionFunc failed<…>
flutter: \^[[38;5;196m└─────────────────────────────────────────────────<…>
Lost connection to device.
```
感觉也像是一样的错

**Comment by doraemonkeys** [comment]
> mac第一个报错没了，第二个还是一样，ios点复制会崩溃:
> 
> ```
> A Dart VM Service on iPhone 15 Pro Max is available at:
> http://127.0.0.1:57960/G6cC1jjW0ac=/
> The Flutter DevTools debugger and profiler on iPhone 15 Pro Max is available at:
> http://127.0.0.1:9101?uri=http://127.0.0.1:57960/G6cC1jjW0ac=/
> flutter: \^[[38;5;196m┌─────────────────────────────────────────────────<…>
> flutter: \^[[38;5;196m│ SocketException: Failed host lookup: 'Unknown' (OS Error: nodename nor servname provided, or not known, errno = 8)<…>
> flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
> flutter: \^[[38;5;196m│ #0   _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)<…>
> flutter: \^[[38;5;196m│ #1   _NativeSocket.connect (dart:io-patch/socket_patch.dart:984:12)<…>
> flutter: \^[[38;5;196m│ #2   _RawSocket.connect (dart:io-patch/socket_patch.dart:1902:26)<…>
> flutter: \^[[38;5;196m│ #3   RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)<…>
> flutter: \^[[38;5;196m│ #4   RawSecureSocket.connect (dart:io/secure_socket.dart:282:22)<…>
> flutter: \^[[38;5;196m│ #5   SecureSocket.connect (dart:io/secure_socket.dart:60:28)<…>
> flutter: \^[[38;5;196m│ #6   Device.doCopyAction (package:wind_send/device.dart:401:35)<…>
> flutter: \^[[38;5;196m│ #7   deviceItemChilden.<anonymous closure>.<anonymous closure> (package:wind_send/main.dart:770:45)<…>
> flutter: \^[[38;5;196m│ #8   DeviceItem.commonActionFunc (package:wind_send/main.dart:581:25)<…>
> flutter: \^[[38;5;196m│ #9   deviceItemChilden.<anonymous closure> (package:wind_send/main.dart:768:30)<…>
> flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
> flutter: \^[[38;5;196m│ 15:25:32.885 (+0:00:02.676064)<…>
> flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
> flutter: \^[[38;5;196m│ ⛔ commonActionFunc failed<…>
> flutter: \^[[38;5;196m└─────────────────────────────────────────────────<…>
> Lost connection to device.
> ```
> 
> 感觉也像是一样的错

把Unknown换成127.0.0.1或者其他ip就行了(长按可以编辑)

**Comment by xgdgsc** [comment]
ios可以，mac报:
<img width="793" alt="截屏2024-02-25 15 45 23" src="https://github.com/doraemonkeys/WindSend/assets/1189869/d7e0b1a3-d435-4060-91fa-23326f1f0a1b">

**Comment by doraemonkeys** [comment]
> ios可以，mac报: <img alt="截屏2024-02-25 15 45 23" width="793" src="https://private-user-images.githubusercontent.com/1189869/307575071-d7e0b1a3-d435-4060-91fa-23326f1f0a1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NDc1MzUsIm5iZiI6MTcwODg0NzIzNSwicGF0aCI6Ii8xMTg5ODY5LzMwNzU3NTA3MS1kN2UwYjFhMy1kNDM1LTQwNjAtOTFmYS0yMzMyNmYxZjBhMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMDc0NzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQyN2RlZmNmNmRmMGM2Y2QxYjQ2ZDQzNjE5NTQzOThlNjMyZjI4OGE2NmE5ZjlmOTk2ZTgyYzhkMGVkNTAxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pnoona4LaLdli43CEfK3RYpQlKEL-PDn9cqqV2cbtmc">

可能是网络权限的原因吧，这个我也不太清楚了
