### ISSUE TITLE
更新具体内容

### ISSUE THREAD

**Issue by Arsiendle** [doraemonkeys/WindSend#25]
我大概是23年12月从酷安慕名而来,那时候大概是0.6.2版本吧,一直没更新.想问问最新都更新了什么具体内容,有必要更新么

**Comment by doraemonkeys** [comment]
有必要
![image](https://github.com/doraemonkeys/WindSend/assets/87186997/05e939b6-b39e-4938-a6aa-d6b5d979d7c8)

**Comment by doraemonkeys** [comment]
更新具体内容在图片里面
