### ISSUE TITLE
Exception : no local ip found

### ISSUE THREAD

**Issue by HaomingChen1998** [doraemonkeys/WindSend#26]
请问为啥一直说Exception : no local ip found, 我已经在firewall里面inbound rules 跟outbound rules都allow windsend.exe的connection了, private嗯public network也都勾选了, 确认是同一个wifi, 也试了手机hotspot, 没开vpn

我看到readme 有说可以用config.yaml文件的secretKeyHex 但是不知道这个文件在哪里

下面是我windows的settings

![Imgur Image](https://i.imgur.com/hnDIHVC.png)

![Imgur Image](https://i.imgur.com/QTJGAnO.png)

**Comment by doraemonkeys** [comment]
Exception : no local ip found是手机上的提示吗

**Comment by HaomingChen1998** [comment]
> Exception : no local ip found是手机上的提示吗？config.yaml跟 windsend.exe在同一个目录

Exception : no local ip found是在windows上提示的, android上面只是显示一个红色感叹号, 没有任何别的提示.

另外确认下config.yaml是在android里面的文件吧, 因为windows folder里面没找到
![Imgur Image](https://i.imgur.com/3Nua4P7.png)

**Comment by doraemonkeys** [comment]
> > Exception : no local ip found是手机上的提示吗？config.yaml跟 windsend.exe在同一个目录
> 
> Exception : no local ip found是在windows上提示的, android上面只是显示一个红色感叹号, 没有任何别的提示.
> ![Imgur Image](https://i.imgur.com/e8EX1rU.png)
> 
> 
> 另外确认下config.yaml是在android里面的文件吧, 因为windows folder里面没找到
> ![Imgur Image](https://i.imgur.com/3Nua4P7.png)

Windows上要使用服务端，也就是在Rust与Go的版本里面选一个，别用flutter那个版本。

另外这好像确实是个bug，能看看你Windows终端上执行ipconfig命令的执行结果吗？

**Comment by FlycanA** [comment]
我这里也没有找到config.yaml，而且右下角也没有出现图标

**Comment by doraemonkeys** [comment]
> 我这里也没有找到config.yaml，而且右下角也没有出现图标

下载错了，看readme文档
![Screenshot_2024-04-04-18-14-11-126_com.github.android.png](https://github.com/doraemonkeys/WindSend/assets/87186997/ad4d310a-5ef1-42df-acb3-0c57ed858143)

**Comment by FlycanA** [comment]
确实没有找到，下载的就是这个，解压之后运行也没有提示选择网络窗口，程序运行后也没有在右下角有提示，6779端口也没有被监听。
我的操作系统信息如下：
![image](https://github.com/doraemonkeys/WindSend/assets/89075536/023f4b22-fc04-42c0-9ff1-cd88c2dada1c)
