### ISSUE TITLE
优化文件调用方案

### ISSUE THREAD

**Issue by Arler2016** [doraemonkeys/WindSend#47]
安卓端的文件选择器（软件主界面最小面的选项）希望可以调用除系统默认文件选择器之外的，比如调用X-PLORE等，有利于快速选取需要同步的文件，提高交互效率。

**Comment by doraemonkeys** [comment]
目前的文件选择器会默认打开你上一次选择的文件夹。

如果你想调用其他的文件管理器，可以直接在文件选择器的左侧边栏选择。
![image](https://github.com/doraemonkeys/WindSend/assets/87186997/1b94ada4-55d1-44fe-b59c-3f019442d071)

**Comment by Arler2016** [comment]
> 目前的文件选择器会默认打开你上一次选择的文件夹。
> 
> 如果你想调用其他的文件管理器，可以直接在文件选择器的左侧边栏选择。 ![image](https://private-user-images.githubusercontent.com/87186997/345289283-1b94ada4-55d1-44fe-b59c-3f019442d071.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDUzODcsIm5iZiI6MTcyMDAwNTA4NywicGF0aCI6Ii84NzE4Njk5Ny8zNDUyODkyODMtMWI5NGFkYTQtNTVkMS00NGZlLWI1OWMtM2YwMTk0NDJkMDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDExMTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MTM2MzBiZjZlYzQwZTdiOTkxMjJkNmE5M2E2ODI3MDg2MTdmM2FiNDBiZTA4MDYzYTFiZWQwYWM4Mzk0MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rpsIX8kSpWntXCZ5v_YPBBE1rsXvN9_xhkrN8XZXIQY)

直接调用第三方文件管理器可以更高效地进入选择界面，只需一步操作即可，而使用上述方式则需要四步。因此，从时间成本的角度看，直接调用第三方文件管理器更为理想。

**Comment by doraemonkeys** [comment]
新版本可以设置使用外部文件管理器了，比如调用X-PLORE就填包名 `com.lonelycatgames.Xplore`
https://github.com/doraemonkeys/WindSend/releases/tag/v1.4.4
