### ISSUE TITLE
无法粘贴复制邮箱地址

### ISSUE THREAD

**Issue by DJ133104** [doraemonkeys/WindSend#5]

**Comment by doraemonkeys** [comment]
我试了没问题，能给个具体的例子吗

**Comment by DJ133104** [comment]
随便一个都不行，31jvhjhxjc@qq.com，我手机复制一个邮箱然后我进软件点粘贴他提示截切板没有内容

**Comment by doraemonkeys** [comment]
![image](https://github.com/doraemonkeys/WindSend/assets/87186997/7103d0aa-8423-4035-bda6-0517f902a95d)
授予一下读取剪切板权限

**Comment by DJ133104** [comment]
![Screenshot_20231016_220305](https://github.com/doraemonkeys/WindSend/assets/114741910/6a4ffe81-7882-4b15-bce3-630fec6c5696)
授予了，粘贴其他文字是正常的，邮箱不行

**Comment by doraemonkeys** [comment]
能提供一下手机系统版本信息吗

**Comment by DJ133104** [comment]
![Screenshot_20231016_230806](https://github.com/doraemonkeys/WindSend/assets/114741910/12d87b05-6e14-4203-9569-298d5c2d3003)

**Comment by doraemonkeys** [comment]
有没有可能是被 origin os 的隐私保护拦截了
![image](https://github.com/doraemonkeys/WindSend/assets/87186997/7a2f92da-e398-403e-8e22-61b7e338b9f1)
