### ISSUE TITLE
[建议]酷友来访

### ISSUE THREAD

**Issue by Arsiendle** [doraemonkeys/WindSend#6]
1.在windows端给web的复制粘贴增设一个快捷键,这样就不需要每次都去右击选择复制或者粘贴了
2.安卓端上设置复制粘贴磁贴,最好使用clash那种逻辑,不需要进入app直接使用功能(反面教材:微信扫码等等,需要先跳转微信再打开扫码功能,偏anywhere了,没必要),当然我看到了目前技术不支持,希望以后有改进的打算时别忘了这个功能/滑稽

**Comment by doraemonkeys** [comment]
好的，我会考虑/手动滑稽

**Comment by doraemonkeys** [comment]
关于加快捷键的建议，我这两天尝试了一下，还是决定不加入这个功能。原因如下
1. 监听快捷键需要在event_loop中不断的poll轮询，导致cpu占用不那么可忽略了
![image](https://github.com/doraemonkeys/WindSend/assets/87186997/cdbd59bc-211b-4939-83c0-13e69583c841)
2. 由于网络波动，按下快捷键后通知的反应时间可能较长，体验不好
3. web的复制粘贴功能本意是应急使用
