### ISSUE TITLE
能不能做个视频讲解一下？

### ISSUE THREAD

**Issue by emol-ch** [doraemonkeys/WindSend#60]
能不能做个视频讲解一下？
我移动端和电脑端都下了，在家同一个局域网内就是连不上，而且电脑端不能驻存在右下角。一点关闭就直接关了

**Comment by doraemonkeys** [comment]
电脑上可能下载错了，下载rust版本的WindSend-S-Rust-x86_64-XXXXX.zip，不是flutter。

**Comment by emol-ch** [comment]
[WindSend-S-Rust-arm64-macos.zip

[WindSend-S-Rust-arm64-windows.zip]


[WindSend-S-Rust-x86_64-linux-musl.zip]

[WindSend-S-Rust-x86_64-linux.zip]
这里面唯一windows也是arm的啊，
![捕获](https://github.com/user-attachments/assets/be866623-8d1f-4caf-8f00-796e3ff15041)

**Comment by doraemonkeys** [comment]
> [WindSend-S-Rust-arm64-macos.zip
> 
> [WindSend-S-Rust-arm64-windows.zip]
> 
> [WindSend-S-Rust-x86_64-linux-musl.zip]
> 
> [WindSend-S-Rust-x86_64-linux.zip] 这里面唯一windows也是arm的啊， ![捕获](https://private-user-images.githubusercontent.com/70947226/380570803-be866623-8d1f-4caf-8f00-796e3ff15041.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODc1ODksIm5iZiI6MTczMDA4NzI4OSwicGF0aCI6Ii83MDk0NzIyNi8zODA1NzA4MDMtYmU4NjY2MjMtOGQxZi00Y2FmLThmMDAtNzk2ZTNmZjE1MDQxLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAzNDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3OTJlOWNjZmMyY2JmNjA5MWM3ZTc2NTFjYmUwMjQxYTU0YTJjYzZjNTFhNzRiNWUxNjAwOTE1YWEzODgwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jzcAH6upsAu9bgFbmK81IgdGRmjKxlw3fJwOogiyi1U)

点击Show all assets，最后一个是x86_64
![image](https://github.com/user-attachments/assets/ada5e70f-0fa4-40a7-a832-2569df586714)

**Comment by emol-ch** [comment]
非常感谢，我对github看来还是不了解啊，难怪看不到呢。
