### ISSUE TITLE
小建议和问题反馈

### ISSUE THREAD

**Issue by BoZhiStudying233** [doraemonkeys/WindSend#65]
你好，非常感谢你做的这个软件，但我在使用过程中遇到了两个问题，我的使用设备是windows11和华为平板，分别安装的版本是WindSend-flutter-arm64-v8a-release.apk
WindSend-flutter-arm64-v8a-release.apk和WindSend-S-Rust-x86_64-windows.zip
。
首先，我发现手机端好像无法设置自动复制，而必须在APP内手动点击复制才能将 电脑端剪切板上的内容 copy到 安卓端，可不可以添加一个自动同步剪切板的功能，让“复制”操作在后台一直运行呢？
第二，我发现从电脑端复制的图片通过软件传到安卓后，会丢失部分信息，如图这是我在电脑端查看平板上的文件，右侧的那个图片文件是我从电脑上复制上去的，左侧是我通过APP同步上去的。可以看到左侧似乎丢失了标题之类的信息。我使用的笔记软件：享做笔记 居然检测不到咱们APP传过来的图片，不会将其视为图片。。。而右侧的则可以检索到。请问这个问题可以解决嘛。
![1cdafea2ede3de605e86b7f028bcfd9](https://github.com/user-attachments/assets/b0c0be8e-fa08-4c00-86c1-6deea223bfdf)
最后感谢作者大大！！！

**Comment by doraemonkeys** [comment]
1. 这个软件设计之初没有考虑在后台同步的使用场景，现在增加这个功能会比较困难；除此之外还有一些其他的权衡与技术上的难点。实在需要可以考虑 [KDE Connect](https://kdeconnect.kde.org) 或 [其他](https://clipshare.coclyun.top) 软件。
   参考：#14
2. 我试了一下把电脑jpg文件复制到手机上，并没有丢失标题信息。可以麻烦计算一下图片的MD5，然后与原图MD5比较吗？如果MD5一致说明并没有丢失标题信息。或者给出具体的复现步骤。
   Windows使用命令 `certutil -hashfile 文件路径 MD5`。

**Comment by doraemonkeys** [comment]
另外复制图片之后可以选择用享做笔记打开或分享到享做笔记，应该可以解决扫描不到图片的问题
![image](https://github.com/user-attachments/assets/d1b7a648-18a4-415e-92e1-12cc424b4325)

**Comment by BoZhiStudying233** [comment]
收到收到，感谢作者大大！！
