### ISSUE TITLE
没有找到可用的服务器

### ISSUE THREAD

**Issue by xxf1113** [doraemonkeys/WindSend#7]

**Comment by xxf1113** [comment]
移动端出现"没有找到可用的服务器"

**Comment by doraemonkeys** [comment]
1. 检查手机和电脑是不是在同一个wifi下面
2. 检查电脑wifi有没有设置为专用网络
![image](https://github.com/doraemonkeys/WindSend/assets/87186997/5cad910d-e9fc-436d-ac20-8998b8cbd94b)


如果还是不行，就用手机给电脑开热点试一试。
